### ISSUE TITLE
Create cocoa pod version

### ISSUE THREAD

**Issue by doctor3w** [cuappdev/ios-networking#4]
This would obviously be useful as a pod so people can stay up to date with the most current files but in a versioned way. One issue though is that things like host, port, common path (e.g. "/api/<version>"), etc need to be specified in the url variable. @kevinchan159 had an interesting solution for apiVersion which was creating a static variable. If we performed this for all of those variables this could provide a nice solution when we go to make this a pod. Are there any other ideas we could use to solve this? A cleaner way may be to use some sort of config struct or class so that you're not setting multiple static vars (same static memory access, just different field offsets rather than multiple different static accesses)

**Comment by doctor3w** [comment]
@AAAstorga @kevinchan159 would you guys mind taking a look at the branch drew/pod where I've started a cocoa pod version. I can't PR it because it's a different commit history

**Comment by kevinchan159** [comment]
@drewsdunne it LGTM. the only thing is that in the README, I think you're missing a newline in the Author section? rest looked fine

**Comment by doctor3w** [comment]
Yup I am, good catch. I'll merge this in then.
